#! /bin/sh

CMD=$1

if [ $1="up" ]; then
  docker compose \
    --file docker-compose.yaml \
    --env-file .env \
    $CMD;
elif [ $1="down" ]; then
  docker compose \
    --file docker-compose.yaml \
    --env-file .env \
    $CMD;
else
  echo "Unkown command '$1'"
fi